"""
Visualization Module

Contains reusable visualization functions for
model evaluation, anomaly detection,
feature importance and data exploration.
"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

def plot_confusion_matrix(
    confusion_matrix,
    title="Confusion Matrix",
    figsize=(6, 5),
    cmap="Blues"
):
    """
    Plot a confusion matrix.

    Parameters
    ----------
    confusion_matrix : array-like
        Confusion matrix.

    title : str
        Plot title.

    figsize : tuple
        Figure size.

    cmap : str
        Heatmap color map.
    """

    plt.figure(figsize=figsize)

    sns.heatmap(
        confusion_matrix,
        annot=True,
        fmt="d",
        cmap=cmap,
        xticklabels=["0", "1"],
        yticklabels=["0", "1"]
    )

    plt.title(title)

    plt.xlabel("Predicted Label")

    plt.ylabel("True Label")

    plt.tight_layout()

    plt.show()

def plot_roc_curve(
    roc_data,
    title="ROC Curve",
    figsize=(6, 5)
):
    """
    Plot the Receiver Operating Characteristic (ROC) Curve.

    Parameters
    ----------
    roc_data : dict
        Dictionary containing:
            - fpr
            - tpr
            - auc

    title : str
        Plot title.

    figsize : tuple
        Figure size.
    """

    plt.figure(figsize=figsize)

    plt.plot(
        roc_data["fpr"],
        roc_data["tpr"],
        linewidth=2,
        label=f"AUC = {roc_data['auc']:.4f}"
    )

    # Random classifier reference
    plt.plot(
        [0, 1],
        [0, 1],
        linestyle="--",
        color="gray",
        label="Random Classifier"
    )

    plt.xlim([0, 1])
    plt.ylim([0, 1.05])

    plt.xlabel("False Positive Rate")

    plt.ylabel("True Positive Rate")

    plt.title(title)

    plt.legend(loc="lower right")

    plt.grid(alpha=0.3)

    plt.tight_layout()

    plt.show()

def plot_feature_importance(
    model,
    feature_names,
    top_n=10,
    title="Feature Importance",
    figsize=(8, 6)
):
    """
    Plot feature importance for tree-based models.

    Parameters
    ----------
    model : trained model
        Trained Random Forest or XGBoost model.

    feature_names : list-like
        List of feature names.

    top_n : int
        Number of top features to display.

    title : str
        Plot title.

    figsize : tuple
        Figure size.
    """

    importance = pd.DataFrame({

        "Feature": feature_names,

        "Importance": model.feature_importances_

    })

    importance = importance.sort_values(
        by="Importance",
        ascending=False
    )

    importance = importance.head(top_n)

    plt.figure(figsize=figsize)

    sns.barplot(
        data=importance,
        x="Importance",
        y="Feature"
    )

    plt.title(title)

    plt.xlabel("Importance Score")

    plt.ylabel("Feature")

    plt.tight_layout()

    plt.show()

def plot_model_comparison(
    comparison_df,
    figsize=(10, 6)
):
    """
    Plot model evaluation metrics for comparison.

    Parameters
    ----------
    comparison_df : pandas.DataFrame
        DataFrame generated by compare_models().

    figsize : tuple
        Figure size.
    """

    metrics = [
        "Accuracy",
        "Precision",
        "Recall",
        "F1 Score"
    ]

    comparison = comparison_df.set_index("Model")

    comparison[metrics].plot(
        kind="bar",
        figsize=figsize
    )

    plt.title("Model Performance Comparison")

    plt.xlabel("Model")

    plt.ylabel("Score")

    plt.ylim(0, 1.05)

    plt.xticks(rotation=0)

    plt.grid(
        axis="y",
        alpha=0.3
    )

    plt.legend(
        title="Metrics"
    )

    plt.tight_layout()

    plt.show()

def plot_correlation_heatmap(
    dataframe,
    figsize=(12, 8),
    cmap="coolwarm",
    annot=False
):
    """
    Plot the correlation matrix of a DataFrame.

    Parameters
    ----------
    dataframe : pandas.DataFrame
        Input DataFrame.

    figsize : tuple
        Figure size.

    cmap : str
        Colormap for the heatmap.

    annot : bool
        Whether to display correlation values.
    """

    correlation = dataframe.corr(numeric_only=True)

    plt.figure(figsize=figsize)

    sns.heatmap(
        correlation,
        cmap=cmap,
        annot=annot,
        fmt=".2f",
        square=True,
        linewidths=0.5,
        cbar=True
    )

    plt.title("Correlation Heatmap")

    plt.tight_layout()

    plt.show()

def plot_feature_distribution(
    dataframe,
    feature,
    bins=30,
    figsize=(8, 5),
    kde=True
):
    """
    Plot the distribution of a numerical feature.
    """

    if feature not in dataframe.columns:
        raise ValueError(
            f"'{feature}' not found in DataFrame.\n"
            f"Available columns: {list(dataframe.columns)}"
        )

    if not pd.api.types.is_numeric_dtype(dataframe[feature]):
        raise TypeError(f"'{feature}' must be a numeric column.")

    plt.figure(figsize=figsize)

    sns.histplot(
        data=dataframe,
        x=feature,
        bins=bins,
        kde=kde
    )

    plt.title(f"Distribution of {feature}")
    plt.xlabel(feature)
    plt.ylabel("Frequency")

    plt.tight_layout()
    plt.show()